# Generated by Django 5.2.4 on 2025-08-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopupNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('show_on_pages', models.CharField(help_text='Список URL через запятую, где показывать попап', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
