# Generated by Django 5.2.4 on 2025-08-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_emailconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Имя'),
        ),
    ]
